export { default as Checkout } from './Checkout';
export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as NotFound } from './NotFound';
export { default as Orders } from './Orders';
export { default as OrdersDetails } from './OrdersDetails';
export { default as Products } from './Products';
export { default as Profile } from './Profile';
export { default as Register } from './Register';
